config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy, :edit, :update]
    resources :reviews, only: [:new, :create, :destroy]
  end
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :stars, presence: true
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true, allow_blank: false
  validates :ingredient_id, :cocktail_id, presence: true, allow_blank: false
  validates_uniqueness_of :ingredient_id, :scope => "cocktail_id"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only:[:show, :edit, :update, :destroy]
  before_action :set_ingredients, only:[:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      respond_to do |format|
        format.html { redirect_to cocktails_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end
    end
  end

  def edit
    @doses = @cocktail.doses
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def set_ingredients
    @ingredients = Ingredient.all
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :stars, :photo, :photo_cache)
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail
  before_action :set_dose, only: [:destroy, :edit, :update]
  before_action :set_ingredients, only: [:edit, :new, :create]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail_id = @cocktail.id
    if @dose.save!
      respond_to do |format|
        format.html { redirect_to cocktail_path(@cocktail) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.js
      end
    end
  end

  def destroy
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  def edit
  end

  def update
    @dose.update(dose_params)
    redirect_to edit_cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_ingredients
    @ingredients = Ingredient.all
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only:[:create, :destroy]
  def new
    @review = Review.new
  end

  def create
    @review = Review.create(review_params)
    @review.cocktail = @cocktail
    if @review.save
      respond_to do |format|
        format.html { redirect_to cocktail_path(@cocktail) }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to cocktail_path(@cocktail) }
        format.js
      end
    end
  end

  def destroy

  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form-cocktail.html.erb
<%= simple_form_for(cocktail, remote: true) do |f| %>
  <%= f.input :name, placeholder: "Cuba Libre" %>
  <%= f.input :stars, collection: 1..5 %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/_form-dose.html.erb
<%= simple_form_for([cocktail, dose], remote: true) do |f| %>
  <%= f.input :description, placeholder: "3cl, 2 slices..." %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cocktails/_modal-cocktail.html.erb
<div class="modal fade" id="cocktail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="form-container">
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <div class="modal-header">
              <h4 class="modal-title text-center" id="myModalLabel">Create a Cocktail</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body-cocktail">
              <%= render 'form-cocktail', cocktail: cocktail %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/_modal-dose.html.erb
<div class="modal fade" id="dose-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="form-container">
        <div class="row">
          <div class="col-sm-10 col-sm-offset-1">
            <div class="modal-header">
              <h4 class="modal-title text-center" id="myModalLabel">Create a Dose!</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body-dose">
              <%= render 'form-dose', cocktail: cocktail, dose: dose %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/_show.html.erb
<div class="col-sm-6 ">
  <div class="card">
    <h4> <%= cocktail.name  %> </h4>
    <ul class="list-inline">
      <li><%= link_to 'Show Recipe', cocktail_path(cocktail), class:"btn btn-success" %></li>
      <li><%= link_to "Delete", cocktail_path(cocktail), class:"btn btn-warning",
  method: :delete,
  data: { confirm: "Are you sure?" } %></li>
    </ul>
  </div>
</div>

app/views/cocktails/create.js.erb
<% if @cocktail.errors.any? %>
  // Render new review form with errors
  $('.modal-body-cocktail').html("<%= j render 'cocktails/form-cocktail', cocktail: @cocktail %>");
  $('#cocktail-modal').modal('show')
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_cocktail = $("<%= j render 'cocktails/show', cocktail: @cocktail %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#cocktails').prepend(new_cocktail);
  // Show the new review with an animation!
  new_cocktail.slideDown();
  // Reset the form
  $('.modal-body-cocktail').html("<%= j render 'cocktails/form-cocktail', cocktail: Cocktail.new %>");
  $('#cocktail-modal').modal('hide')
<% end %>

app/views/cocktails/edit.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name, placeholder: "Cuba Libre" %>
        <%= f.input :stars, collection: 1..5 %>
        <div class="form-action">
          <%= f.button :submit, class: "btn btn-primary" %>
          <%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div id="wrapper">
  <div class="card-container">
    <div class="row">
      <div id="cocktails">
        <% @cocktails.each do |cocktail| %>
          <%= render 'cocktails/show', cocktail: cocktail %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="button-container text-center">
    <div>
      <%= link_to "Home", pages_home_path, class:"btn btn-primary" %>
    </div> 
    <button type="button" id="cocktail-modal-button" class="btn btn-primary" data-toggle="modal" data-target="cocktail-modal">
      Create a Cocktail
    </button>
  </div>
</div>

<%= render 'modal-cocktail', cocktail: Cocktail.new %>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#cocktail-modal-button').on("click", function() {
        $('#cocktail-modal').modal('show')
      });
    });
  <% end %>
<% end %>

app/views/cocktails/new.html.erb
<h1>Create a New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h2><%= @cocktail.name %>'s Recipe: </h2>
      <div id="doses-<%= @cocktail.id %>"></div>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <%= render 'doses/show', dose: dose %>
        <% end %>
      </ul>

      <button type="button" id="dose-modal-button" class="btn btn-primary" data-toggle="modal" data-target="dose-modal">
        Add a dose to your Cocktail
      </button>

      <%= link_to 'Add a Review', new_cocktail_review_path(@cocktail), class: "btn btn-primary" %>
      <%= link_to 'Edit Cocktail', edit_cocktail_path(@cocktail), class:"btn btn-success" %>
      </br>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

<%= render 'modal-dose', cocktail: @cocktail, dose: Dose.new %>

<div id="new_review">
  <%= render 'reviews/form-review', cocktail: @cocktail, review: Review.new %>
</div>

<div id="reviews-cocktail-<%= @cocktail.id %>">
  <% if @cocktail.reviews.blank? %>
    <h6>Be the first to leave a review for <%= @cocktail.name %></h6>
  <% else %>
    <% @cocktail.reviews.each do |review| %>
    <ul>
      <%= render 'reviews/show', review: review %>
    </ul>
    <% end %>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#dose-modal-button').on("click", function() {
        $('#dose-modal').modal('show')
      });
    });
  <% end %>
<% end %>

app/views/doses/_form.html.erb
<div class="form-container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
    <h3 class="text-center">Define the Recipe of your Cocktail</h3>

    <%= simple_form_for([@cocktail, @dose], remote: true) do |f| %>
      <%= f.input :description, placeholder: "3cl, 2 slices..." %>
      <%= f.input :ingredient_id, collection: @ingredients %>
      <div class="form-action">
        <%= f.button :submit, class: "btn btn-primary" %>
        <%= link_to 'Back', cocktails_path, class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/doses/_show.html.erb
<li><%= dose.description %> of <%= @ingredients.find(dose.ingredient_id).name %></li>

app/views/doses/create.js.erb
<% if @dose.errors.any? %>
  // Render new review form with errors
  $('.modal-body-dose').html("<%= j render 'cocktails/form-dose', cocktail: @cocktail, dose: @dose %>");
  $('#dose-modal').modal('show')
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_dose = $("<%= j render 'doses/show', dose: @dose %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#doses-<%= @cocktail.id %>').prepend(new_dose);
  // Show the new review with an animation!
  new_dose.slideDown();
  // Reset the form
  $('.modal-body-dose').html("<%= j render 'cocktails/form-dose', cocktail: @cocktail, dose: Dose.new %>");
  $('#dose-modal').modal('hide')
<% end %>

app/views/doses/edit.html.erb
<%= render 'form' %>

app/views/doses/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Cocktail Shaker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield(:after_js) %>

</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="title_1">
    The Cocktail Shaker
  </div>
  <div class="title_2">
    Store and share all your Recipes!
  </div>
  <div>
    <%= link_to "See all Cocktails", cocktails_path, class:"btn btn-primary" %>
  </div> 
  <div class="table">
    <div class="glassHead">
      <div class="strawContainer">
        <div class="straw">
        </div>
        <div class="lemon">
        </div>
        <div class="ice">
        </div>
        <div class="ice ice2">
        </div>
        <div class="ice ice3">
        </div>
      </div>
    </div>
    <div class="liquid2">
    </div>
    <div class="liquid">
    </div>
    <div class="glassBar">
    </div>
    <div class="glassFoot">
    </div>
  </div>
</div>

app/views/reviews/_form-review.html.erb
<%= simple_form_for([cocktail, review], remote: true) do |f| %>
  <%= f.input :content, placeholder: "Very nice Cocktail!" %>
  <div class="form-action">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
  $('#new_review').html("<%= j render 'reviews/form-review', cocktail: @cocktail, review: @review %>");
<% else %>
  var new_review = $("<%= j render 'reviews/show', review: @review %>").hide();
  $('#reviews-cocktail-<%= @cocktail.id %>').prepend(new_review);
  new_review.slideDown();
  $('#new_review').html("<%= j render 'reviews/form-review', cocktail: @cocktail, review: Review.new %>");
<% end %>